- name: Copy helm configuration
  copy:
    dest: "/home/{{ ansible_user }}/helm.yaml"
    content: |
      ---
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: tiller-manager
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: tiller-manager
        namespace: kube-system
      ---
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller-manager
        namespace: kube-system


- name: Create helm k8s resources
  shell: "kubectl apply -f /home/{{ ansible_user }}/helm.yaml"

- name: Helm init
  shell: "helm init --upgrade --service-account tiller-manager"

- name: Clean up working files
  file:
    path: "helm.yaml"
    state: absent

