- hosts: "cluster_{{ lookup('env','CLUSTER_NAME') }}-{{ lookup('env','ENVIRONMENT') }}-{{ lookup('env','NAME_SUFFIX') }}:!role_bastion"
  become: no
  remote_user: "ubuntu"

  roles:
    #- install-docker
 
