version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
networks:
  default:
    external:
      name: genesis-dockernet


